login_status/urls.py
from django.conf.urls import url
from .views import delete_status, add_status, index, status
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^status$', status, name='status'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id>[0-9999]+)/$', delete_status, name='delete_status'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


]

profile_page/urls.py
from django.conf.urls import url
from .views import index, post_linkedin_data, toggle_nilai
from .skills_api import SkillAPI

urlpatterns = (
    url(r'^$', index, name='index'),
    url(r'^linkedin/$', post_linkedin_data, name='linkedin'),
    url(r'^nilai/$', toggle_nilai, name='nilai'),
    url(r'^api/skills(?:/(?P<pk>[0-9]+))?/$', SkillAPI.as_view(), name='skills'), # POST, DELETE
)

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import login_status.urls as login_status
import profile_page.urls as profile
import cari_mahasiswa.urls as cari_mahasiswa
import riwayat_page.urls as riwayat
from django.views.generic.base import RedirectView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login-status/',include(login_status, namespace='login-status')),
    url(r'^profile/',include(profile, namespace='profile')),
    url(r'^cari_mahasiswa/',include(cari_mahasiswa, namespace='cari_mahasiswa')),
    url(r'^riwayat/',include(riwayat, namespace='riwayat')),
    url(r'^$', RedirectView.as_view(url='profile/', permanent='true'), name='index'),
    url(r'^logout/$', login_status.auth_logout, name='logout'),
]

profile_page/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    npm = models.CharField(max_length=32, primary_key=True)
    name = models.CharField(max_length=1286, null=True)
    email = models.CharField(max_length=646, null=True)
    linkedin = models.CharField(max_length=256, null=True)
    headline = models.TextField(null=True)
    picture_url = models.TextField(null=True)
    showing_score = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} ({}): {}'.format(self.name if self.name else 'unnamed', self.npm, self.email if self.email else 'no email')

    def is_connected_to_linkedin(self):
        return self.linkedin is not None

    def get_angkatan(self):
        return '20' + str(self.npm)[:2]

class Skill(models.Model):
    INTERMEDIATE = 'I'
    ADVANCED = 'A'
    EXPERT = 'E'
    LEGEND = 'L'
    SKILL_LEVELS = (
        (INTERMEDIATE, 'Intermediate'),
        (ADVANCED, 'Advanced'),
        (EXPERT, 'Expert'),
        (LEGEND, 'Legend'),
    )
    profile = models.ForeignKey(Profile)
    skill_title = models.CharField(max_length=32)
    skill_level = models.CharField(
        max_length=1,
        choices=SKILL_LEVELS,
        default=INTERMEDIATE,
    )

    def __str__(self):
        return '{} ({}): {}'.format(self.skill_title, self.get_skill_level_display(), self.profile.name)

class Status(models.Model):
    account = models.ForeignKey(Profile)
    message = models.TextField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True)

profile_page/views.py
from login_status import require_login, get_logged_in_user_npm
from profile_page import render_with_profile, get_profile_by_npm, should_profile_shows_score
from django.http import HttpResponse, HttpResponseBadRequest
from .models import Profile, Status

# Create your views here.

TEMPLATE = 'profile/profile.html'

@require_login
def index(request):
    check_profile(request)
    return render_with_profile(request, TEMPLATE, {
        'profile_page': True, 
        'editing':True if 'edit' in request.GET and request.GET['edit'] else False,
        'showing_score': should_profile_shows_score(get_logged_in_user_npm(request))
    })

def check_profile(request):
    '''
    Akan membuat profile baru apabila belum ada di DB
    '''
    npm = get_logged_in_user_npm(request)
    if not get_profile_by_npm(npm):
        profile = Profile(npm=npm)
        profile.save()
    
@require_login
def post_linkedin_data(request):
    if request.method == 'POST':
        profile = get_profile_by_npm(get_logged_in_user_npm(request))
        profile.name = request.POST['name']
        profile.linkedin = request.POST['url']
        profile.picture_url = request.POST['pic'] if 'pic' in request.POST else None
        profile.email = request.POST['email'] if 'email' in request.POST else None
        profile.headline = request.POST['headline'] if 'headline' in request.POST else None
        profile.save()
        return HttpResponse(status=201)

@require_login
def toggle_nilai(request):
    if request.method == 'POST':
        profile = get_profile_by_npm(get_logged_in_user_npm(request))
        if request.POST['show'] == '1':
            profile.showing_score = True
        else:
            profile.showing_score = False
        profile.save()
        return HttpResponse(status=201)

profile_page/templates/profile/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="PPW Yudhis, Raka, Wildan, Azhar">

        <title>{% block page_title %} Winners win {% endblock %}</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

        <!-- Base CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">

        <!-- Additional resources -->
        {% block page_resources %} {% endblock %}
 
    </head>
    <body>
        <script>
            const startUpFunctions = [];
            const csrfToken = '{{csrf_token}}';
        </script>
        <header>
            {% include "profile/header.html" %}
        </header>
        <section class="container flex-grow mt-3">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4 mt-2">
                    {% block base_profile %}
                    {% include "profile/cards/brief_profile.html" %}
                    {% endblock %}
                </div>
                <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 mt-2">
                    {% block content %}
                    3
                    {% endblock %}
                </div>
            </div>
        </section>
        <footer>
            <nav class="navbar navbar-light bg-light text-nowrap">
                <a class="navbar-brand text-truncate" href="#">Made with love by Yudhis, Raka, Wildan, Azhar</a>
            </nav>
        </footer>        
        <!-- JQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <!-- QUnit -->
        <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">
        <script src="https://code.jquery.com/qunit/qunit-2.4.1.js"></script>

        <!-- Bootstrap stuffs -->
        <script src="{% static 'js/bootstrap.bundle.js' %}" ></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        
        {% block javascript %} {% endblock %}
        

        <script>
        $(document).ready(() => {
            $('[data-toggle="popover"]').popover()
            for(var i = 0; i < startUpFunctions.length; i++) startUpFunctions[i]()
            console.log(startUpFunctions.length + ' start up function(s) executed!')
        })
        </script>

        <!-- JQuery is already loaded here -->
        {% block bottom_script %}{% endblock %}

    </body>
</html>

profile_page/templates/profile/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-lab-8">
    <div class="container">
        <a class="navbar-brand header-title" href="#">{% block page_navbar_header %} Winners {% endblock %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapse-navbar" aria-controls="collapse-navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapse-navbar">
            <ul class="navbar-nav">
                <li class="nav-item {% if profile_page %} active {% endif %}"><a class="nav-link" href="{% url 'profile:index' %}">Profile</a></li>
                <li class="nav-item {% if riwayat_page %} active {% endif %}"><a class="nav-link" href="{% url 'riwayat:index' %}">Riwayat</a></li>
                <li class="nav-item {% if status_page %} active {% endif %}"><a class="nav-link" href="{% url 'login-status:status' %}">Status</a></li>
                <li class="nav-item {% if teman_page %} active {% endif %}"><a class="nav-link" href="{% url 'cari_mahasiswa:index' %}">Teman</a></li>
            </ul>
            <div class="mr-auto mt-2 mt-lg-0">
            </div>
            <div class="my-2 my-lg-0">
                {% if profile.name %}
                <span class="user-name">
                    {{ profile.name }}
                </span>
                <span><a href="{% url 'logout' %}" class="btn btn-danger">Logout</a></span>
                {% else %}
                {% endif %}
            </div>
        </div>
    </div>
</nav>

profile_page/templates/profile/profile.html
{% extends 'profile/base.html' %}

{% block bottom_script %}
{% load staticfiles %}
<script src="{% static 'js/profile.js' %}"></script>
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   810och89vljlk6
    authorize: true
    scope: r_basicprofile r_emailaddress
</script>
{% endblock %}

{% block page_resources %}
<link rel='stylesheet' type='text/css' href='{% static 'css/font-awesome.css' %}' />
{% endblock %}

{% block content %}
<div class="card mb-5">
    <div class="card-header">
        Profile 
        <span class="user-name">
            {% if profile.is_complete %}
            {{profile.name}}
            {% else %}
            belum lengkap
            {% endif %}
        </span>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <b>
                    NPM
                </b>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                {{profile.npm}}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <b>
                    Email
                </b>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                <span class="user-email">{{profile.email}}</span>
            </div>
        </div>

    
        <div class="row mb-3">
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <b>
                    Linkedin
                </b>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                {% if profile.is_complete %}
                <a href="{{profile.linkedin}}">{{profile.linkedin}}</a>
                {% else %}
                <p class="kosong">Kosong</p>
                <a href="#"><img class="linkedin d-none" src="https://lh3.googleusercontent.com/NDLbBmBiX6YSto4F9I_FA6Ej919fGZjBfNpns2epTlND8Ora0F2K5GIwa8ZoXfHpUtisKP4pzQcxmSrN_7xIT_Gksr8LXSGoW3gSD8hfaZn7qE9evx6pt8XrelM-rborj8yUeOhobkGASSpNGfGXEMnbVn0FOLnPAGWj3TyWfEP-BfOKUMEmkq8trkGnj3N0jBT6I3ZPYCA0kTR4Nd1oR8MvBsBVYKpyBbxhY_zub0m8f6euvFGSxo-jBwhK0jyETDbw111zN1AeIod73daPT9NSiLpV2AAT4bQT-wNXwypTJE-wb4qgMfebCcxZoD9xgJtwxxFri2PRrW4dwruTQOr9KfDR6GFniM9aA0ypnyovKnm2KsAzMscvI_CFM2TDKzaOAAGPeveu5mo_s2uLDh7d0spN1e1IXuCOiHkv0ogJBI7X08vHkMWBO-XdCizBRDY4lNWOgbDKDEnYzhdQoKMwCOJuIFOFOHZiaGz__aK3KYkCLEN5xMxsrnhY1ElH_-r3SJLwv2gwrraBg7uIPFWjcYWeOysbsp44XVEXebuQqiW9_56SFWbsvNYmXE_r9QdZLe0kIekskVfypL5uDacwwqR-Ep68uTZ_HvPiqJQ0hCOC_-oz5ylE8rHfizYJru8taIaGN5-Ye1jAeIW-HuuK5Crevqr3akc=w678-h135-no"></a>
                <span id="linkedin-url"></span>
                {% endif %}
            </div>
        </div>
        
        <div class="row mb-3" id="keahlian">
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <b>
                    Keahlian
                </b>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9" id="skill-column">
                <div id="skill-list">
                    {% if profile.skills %}
                    {% for skill in profile.skills %}
                    <div class="row ml-1 mb-2" id="delete-skill-{{skill.id}}">{{skill.title}} <span 
                        class="badge badge-{% if skill.level == 'Intermediate' %}success{% endif %}{% if skill.level == 'Advanced' %}info{% endif %}{% if skill.level == 'Expert' %}primary{% endif %}{% if skill.level == 'Legend' %}danger{% endif %} ml-1">
                        {{skill.level}}</span>
                        <button type="button" class="btn btn-light delete-skill btn-sm ml-2 d-none" onclick="buttonDeleteSkill($('#delete-skill-{{skill.id}}'), {{skill.id}})" ><i class="fa fa-times" aria-hidden="true"></i></button>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p id="skill-kosong">Kosong</p>
                    {% endif %}
                </div>
                <div class="form-row add-skill mt-3 d-none" id="skill-form">
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                        <label class="sr-only" for="skill-title">Tambah Keahlian</label>
                        <input type="text" class="form-control mb-2 mb-sm-0" id="skill-title" placeholder="Tambah Keahlian" maxlength="16"
                        pattern=".{2,16}" data-toggle="popover" data-trigger="focus" data-placement="bottom" data-content="Judul keahlian minimum 2 karakter dan maksimum 16 karakter">
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                        <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="skill-level">
                            <option value="I" disabled selected>Level..</option>
                            <option value="I">Intermediate</option>
                            <option value="A">Advanced</option>
                            <option value="E">Expert</option>
                            <option value="L">Legend</option>
                          </select>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                        <button type="button" class="btn btn-primary btn-add-skill" id="submit-skill">Tambahkan</button>
                    </div>
                </div>

            </div>
        </div>
        <div class="row ml-1 mt-2 d-none nilai">
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-primary btn-sm active" onclick="toggleNilai(true)">
                    <input type="radio" name="adsa" id="show-score" autocomplete="off" > Tampilkan nilai
                </label>
                <label class="btn btn-primary bt-sm " onclick="toggleNilai(false)">
                    <input type="radio" name="dsds" id="hide-score" autocomplete="off" checked> Sembunyikan nilai
                </label>
            </div>
        </div>
    </div>
</div>
<script>
    const editingFromStart = {% if editing %}true{% else %}false{% endif %}
    const showingScoreFromStart = {% if showing_score %}true{% else %}false{% endif %}
    startUpFunctions.push(() => {
        $('.nilai').hide()
        $('.nilai').removeClass('d-none')
        $('.delete-skill').hide()
        $('.delete-skill').removeClass('d-none')
        $('.linkedin').hide()
        $('.linkedin').removeClass('d-none')
        $('.add-skill').hide()
        $('.add-skill').removeClass('d-none')
        if (!showingScoreFromStart) {
            $('#hide-score').trigger("click")
        }
    })
</script>
{% endblock %}