login_status/urls.py
from django.conf.urls import url
from .views import delete_status, add_status, index, status
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^status$', status, name='status'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id>[0-9999]+)/$', delete_status, name='delete_status'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import login_status.urls as login_status
import profile_page.urls as profile
import cari_mahasiswa.urls as cari_mahasiswa
import riwayat_page.urls as riwayat
from django.views.generic.base import RedirectView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login-status/',include(login_status, namespace='login-status')),
    url(r'^profile/',include(profile, namespace='profile')),
    url(r'^cari_mahasiswa/',include(cari_mahasiswa, namespace='cari_mahasiswa')),
    url(r'^riwayat/',include(riwayat, namespace='riwayat')),
    url(r'^$', RedirectView.as_view(url='profile/', permanent='true'), name='index'),
    url(r'^logout/$', login_status.auth_logout, name='logout'),
]

login_status/models.py
from django.db import models

login_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(label='', widget=forms.Textarea(attrs=attrs), required=True, max_length=300)

login_status/views.py
import datetime
from django.urls import reverse
from profile_page import render_with_profile as render
from django.shortcuts import render as render_ori
from django.http import HttpResponseRedirect
from .forms import Status_Form
from django.utils import timezone
from .utils import require_login
from profile_page import get_profile_by_npm
from login_status import get_logged_in_user_npm
from profile_page.models import Status

import pytz

# Create your views here.
response = {'status_form': Status_Form, 'logged_in': False, 'status_page': True}


def index(request):
    if 'kode_identitas' in request.session:
        return HttpResponseRedirect(reverse('index'))
    else:
        html = 'login_status/login.html'
    return render_ori(request, html, response)

@require_login
def status(request):
    html = 'update_status.html'
    kode_identitas = request.session['kode_identitas']
    npm = get_logged_in_user_npm(request)
    account = get_profile_by_npm(npm)
    allStatus = Status.objects.filter(account=account)
    response['allStatus'] = allStatus
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        npm = get_logged_in_user_npm(request)
        account = get_profile_by_npm(npm)
        status = Status(account=account, message=request.POST['message'])
        status.save()
        allStatus = Status.objects.filter(account=account)
        response['allStatus'] = allStatus
        html = 'update_status.html'
        return HttpResponseRedirect(reverse('login-status:status'))
    else:
        return HttpResponseRedirect(reverse('login-status:status'))


def delete_status(request, id):
    status_target = Status.objects.all().get(pk=id)
    status_target.delete()
    return HttpResponseRedirect(reverse('login-status:status'))

# ======================================================================== #

login_status/templates/login_status/login.html
<!DOCTYPE html>
<html>
<title>Login</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

<style>
body,h1 {font-family: "Raleway", sans-serif}
body, html {height: 100%}

.bgimg {
    background-image: url('https://www.digitalplatforms.co.za/wp-content/uploads/2015/11/Website-Design-Background.png');
    min-height: 100%;
    background-position: center;
    background-size: cover;
}
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4a5870;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
<body>

  <div class="bgimg w3-display-container w3-animate-opacity w3-text-white">
  <div class="w3-display-topleft w3-padding-large w3-xlarge">
  </div>
  <div class="w3-display-middle">
    <h1 class="w3-jumbo w3-animate-top">Selamat datang di Tugas 2</h1>
    <hr class="w3-border-grey" style="margin:auto;width:40%">
    {%if error%}
    <p> {{error}}</p>
    {%endif%}
    <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login Mahasiswa</button>  </div>

</div>




<div id="id01" class="modal">

  <form class="modal-content animate" action="{% url 'login-status:auth_login' %}" method="POST">
    {% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="https://sso.ui.ac.id/cas/themes/ui/logo.png">
      <h1 style="color:black; font-size: 100%;">Silahkan Login menggunakan SSO</h1>

    </div>

    <div class="container">
      <label><b>Username</b></label>
      <input type="text" placeholder="Enter Username" id="username" name="username" required>

      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" id="password" name="password" required>

      <button type="submit">Login</button>
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>
</html>

login_status/templates/login_status/profile.html
<h2>Berhasil Login</h2>