login_status/urls.py
from django.conf.urls import url
from .views import delete_status, add_status, index, status
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^status$', status, name='status'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id>[0-9999]+)/$', delete_status, name='delete_status'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),


]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import login_status.urls as login_status
import profile_page.urls as profile
import cari_mahasiswa.urls as cari_mahasiswa
import riwayat_page.urls as riwayat
from django.views.generic.base import RedirectView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login-status/',include(login_status, namespace='login-status')),
    url(r'^profile/',include(profile, namespace='profile')),
    url(r'^cari_mahasiswa/',include(cari_mahasiswa, namespace='cari_mahasiswa')),
    url(r'^riwayat/',include(riwayat, namespace='riwayat')),
    url(r'^$', RedirectView.as_view(url='profile/', permanent='true'), name='index'),
    url(r'^logout/$', login_status.auth_logout, name='logout'),
]

login_status/models.py
from django.db import models

login_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(label='', widget=forms.Textarea(attrs=attrs), required=True, max_length=300)

login_status/views.py
import datetime
from django.urls import reverse
from profile_page import render_with_profile as render
from django.shortcuts import render as render_ori
from django.http import HttpResponseRedirect
from .forms import Status_Form
from django.utils import timezone
from .utils import require_login
from profile_page import get_profile_by_npm
from login_status import get_logged_in_user_npm
from profile_page.models import Status

import pytz

# Create your views here.
response = {'status_form': Status_Form, 'logged_in': False, 'status_page': True}


def index(request):
    if 'kode_identitas' in request.session:
        return HttpResponseRedirect(reverse('index'))
    else:
        html = 'login_status/login.html'
    return render_ori(request, html, response)

@require_login
def status(request):
    html = 'update_status.html'
    kode_identitas = request.session['kode_identitas']
    npm = get_logged_in_user_npm(request)
    account = get_profile_by_npm(npm)
    allStatus = Status.objects.filter(account=account)
    response['allStatus'] = allStatus
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        npm = get_logged_in_user_npm(request)
        account = get_profile_by_npm(npm)
        status = Status(account=account, message=request.POST['message'])
        status.save()
        allStatus = Status.objects.filter(account=account)
        response['allStatus'] = allStatus
        html = 'update_status.html'
        return HttpResponseRedirect(reverse('login-status:status'))
    else:
        return HttpResponseRedirect(reverse('login-status:status'))


def delete_status(request, id):
    status_target = Status.objects.all().get(pk=id)
    status_target.delete()
    return HttpResponseRedirect(reverse('login-status:status'))

# ======================================================================== #

login_status/templates/update_status.html
{% extends "profile/base.html" %}
{% load staticfiles %}
{% load static %}

{% block page_resources %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
{% endblock %}

{% block content %}
    <section name="form">
        <h2>Update Status</h2>
        <form id="form" method="POST" action="{% url 'login-status:add_status' %}">
            {% csrf_token %}
            {{ status_form }}
            <br>
            <button type="submit" class="btn-status btn-default"><span>Post</span></button>
        </form>
        <br>
    </section>

    <section name="status history">
        <div class="flex">
            {% for i in allStatus reversed %}
                <div class="flex-item mb-3">
                    <div class="list-status-photo-status">
                        <img class="avatar_image" id="status-photo"
                             src="{{ i.account.picture_url }}">
                    </div>
                    <div class="list-status">
                        <b class="author_name"> {{ i.account.name }} </b>
                        <p class="status_message"> {{ i.message }} </p>
                        <p class="created_time"> {{ i.created_date }} </p>
                    </div>
                    <div class="to-do-list-delete">
                        <div class="to-do-list-delete-button" data-id="{{ i.id }}">Delete</div>
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
    </section>
{% endblock %}

{% block bottom_script %}
<script type="application/javascript">
    $(".to-do-list-delete-button").click(function () {
        var id = $(this).data('id');
        location.href = "delete_status/" + id;
    });
</script>
{% endblock %}